"""initial migration

Revision ID: 866f1de520b6
Revises: eeaaf03c1f35
Create Date: 2016-07-17 16:57:32.904609

"""

# revision identifiers, used by Alembic.
revision = '866f1de520b6'
down_revision = 'eeaaf03c1f35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_comments_disabled'), 'comments', ['disabled'], unique=False)
    op.drop_index('ix_comments_disable', table_name='comments')
    op.drop_column('comments', 'disable')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disable', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_comments_disable', 'comments', ['disable'], unique=False)
    op.drop_index(op.f('ix_comments_disabled'), table_name='comments')
    op.drop_column('comments', 'disabled')
    ### end Alembic commands ###
