"""initial migration

Revision ID: c7a4aac1c97d
Revises: 1a9733b636ff
Create Date: 2016-07-15 21:45:45.147790

"""

# revision identifiers, used by Alembic.
revision = 'c7a4aac1c97d'
down_revision = '1a9733b636ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
